### ISSUE TITLE
Profile Setting not available

### ISSUE THREAD

**Issue by tusharjain0022** [EricLiclair/dev_card#1]
### Bug Report
- Profile setting option in navbar redirects to 404 page

#### Steps to Reproduce
- Signin/Login in your account
- Go to Navbar>Profile Setting

#### Supporting Video

https://user-images.githubusercontent.com/59157988/148006438-ceb479aa-4e12-4a34-8e12-3de73ab1747b.mp4

**Comment by EricLiclair** [comment]
Thanks for the mention @tusharjain0022 
Will be adding the profile view soon.

**Comment by EricLiclair** [comment]
Fixed with #4
